### ISSUE TITLE
Cannot get 'pause' of null

### ISSUE THREAD

**Issue by tjvg91** [Harvest-Dev/ng-walkthrough#27]
Why do I get this error?
```
ERROR TypeError: Cannot read property 'pause' of null`
    at WalkthroughComponent.open (angular-walkthrough.js:704)`
    at WalkthroughFlowComponent.start (angular-walkthrough.js:1964)`
```

![image](https://user-images.githubusercontent.com/5625925/47424530-744ea480-d7ba-11e8-8e89-d814d3140d35.png)

This is my code:
```
@ViewChild('walkFlow1') walkFlow1: WalkthroughFlowComponent;
this.walkFlow1.start();
```

This is my markup:
```
<ng-walkthrough-flow
   focusBackdrop="true"
   focusHighlightAnimation="true"
   closeButton="true"
   closeAnywhere="false"
   showArrow="true"
   radius="auto" #walkFlow1>

   <ng-walkthrough id="walk-to-title"
      focusElementSelector="#hymnTitle"
      contentText="Tap to browse hymns in the hymnal">
   </ng-walkthrough>

</ng-walkthrough-flow>
```

**Comment by Zefling** [comment]
It's really your code ? Where is the start is the lifecycle of your component ?

**Comment by Zefling** [comment]
“lifecycle of your component” : `ngOnInit`, `ngAfterContentInit`, `ngAfterViewInit`

**Comment by tjvg91** [comment]
I put my code inside ionViewDidLoad

```
...
import { Component, OnDestroy, ViewChild, ElementRef, HostListener } from '@angular/core';
import { WalkthroughFlowComponent } from 'angular-walkthrough'
...
@IonicPage()
@Component({
...
})
export class ReaderPage implements OnDestroy{
   ...
   @ViewChild('walkFlow1') walkFlow1: WalkthroughFlowComponent;
   ...
   constructor(...){...}

   ionViewDidLoad(){
      ...
      this.walkFlow1.start();
   }

   ngDestroy(){...}
```

No `ngOnInit`, `ngAfterContentInit`, or `ngAfterViewInit`

**Comment by Zefling** [comment]
Hoo, it's with Ionic... Sorry, it don't use it.

**Comment by Zefling** [comment]
For information, the module injects an external component in the body. Without out body, this module doesn't work. 
![2018-10-26_14h31_06](https://user-images.githubusercontent.com/3032555/47566366-d2e76000-d92b-11e8-9eb8-82460cbcb5ef.png)

**Comment by tjvg91** [comment]
Does the lifecycle matter that much? When do the walkthrough elements appear? And yes I have that `walkthrough-container` element.

**Comment by Zefling** [comment]
I have add a fix. Please, test with 0.7.3.
