### ISSUE TITLE
Arrow not showing

### ISSUE THREAD

**Issue by brampurnot** [Harvest-Dev/ng-walkthrough#5]
Hello,

I have a small problem with the showArrow. It is not shown at first. However if I resize the screen or re-open the walkthrough, it is shown.

Anyone else experiencing this issue?

Bram

**Comment by Zefling** [comment]
With which browser, please?

**Comment by brampurnot** [comment]
Firefox and Chrome...Didn't test any other browser.

**Comment by Zefling** [comment]
Hmm, it's strange.  I don't manage to reproduce this on Firefox and Chrome.
It's possible to make a test case ?

**Comment by brampurnot** [comment]
I discovered the problem (still not sure how it can be fixed). Apparently the issue occurs only for elements that are dynamically created. 

I'm actually building a kind of notification center in my website. when an error occurs, a new notification is dynamically added. This notification can contain a button to start the walkthrough process. If I click this dynamically generated button, the arrow is not shown. 

When the button is already existing, i.e. not dynamically added, then there is no problem and the button is added. I'll see if I can create a splunker example somewhere next week.
