### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by mpadmaraj** [Harvest-Dev/ng-walkthrough#9]
Do you have a branch which I can use for my angular 4 code. I do see that the tag you have in description says "angular4". Or if you can suggest how I can modify this to work with Angular 4, that would be great!

**Comment by Zefling** [comment]
I'm sorry, I forgot to change the meta tags.
I'm not sure it's easy.
Do you have difficulty passing on angular 5?

You can try to take over the project with the configuration of a 0.4.x release.
